name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-cpp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make -C C++
    - name: Archive
      run: tar -zcvf build-cpp.tar.gz C++/queens
    - uses: actions/upload-artifact@v4.3.1
      with:
        name: build-cpp
        path: build-cpp.tar.gz

  build-java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make -C Java
    - uses: actions/upload-artifact@v4.3.1
      with:
        name: build-java
        path: Java/queens.jar

  build-go:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: go build -C Go
    - name: Archive
      run: tar -zcvf build-go.tar.gz Go/queens
    - uses: actions/upload-artifact@v4.3.1
      with:
        name: build-go
        path: build-go.tar.gz

  build-rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd Rust
        cargo build -r
    - name: Archive
      run: tar -zcvf build-rust.tar.gz Rust/target/release/queens
    - uses: actions/upload-artifact@v4.3.1
      with:
        name: build-rust
        path: build-rust.tar.gz

  launch-cpp:

    runs-on: ubuntu-latest
    needs: build-cpp

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: build-cpp
    - name: Unarchive
      run: tar -zxvf build-cpp.tar.gz
    - name: Launch
      run: ./launch.py 100 1000 5 3 C++/queens

  launch-java:

    runs-on: ubuntu-latest
    needs: build-java

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: build-java
    - name: Launch
      run: ./launch.py 100 1000 5 3 java -jar queens.jar

  launch-python:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Launch
      run: ./launch.py 100 1000 5 3 Python/queens.py

  launch-js:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Launch
      run: ./launch.py 100 1000 5 3 node JS/queens.js

  launch-php:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Launch
      run: ./launch.py 100 1000 5 3 php PHP/queens.php
